site_name: Envars
site_description: Application Config As Code

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Configuration File: user-guide/01-configuration-file.md
    - CLI Commands: user-guide/02-cli-commands.md
    - Secret Management: user-guide/03-secret-management.md
    - Variable Templating: user-guide/04-variable-templating.md
    - Dynamic Variables: user-guide/05-dynamic-variables.md
    - Validation: user-guide/06-validation.md
  - API Reference:
    - Library Usage: api-reference/index.md
    - Data Models: api-reference/models.md
  - Project:
    - Contributing: project/contributing.md
    - Security: project/security.md
    - Changelog: project/changelog.md
    - License: project/license.md