name: PR Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install uv
        uv sync
    - name: Test with pytest
      env:
        AWS_DEFAULT_REGION: us-east-1
      run: uv run pytest

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv sync

      - name: Install pre-commit hooks
        run: |
          uv run pre-commit install-hooks

      - name: Run pre-commit checks
        run: |
          uv run pre-commit run --all-files
